---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: instance
    image: ubuntu
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
